[
    {
        "userId": 41,
        "fullName": "Chiru",
        "email": "roz",
        "phone": "123",
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "new  services, Standard Room Booking, new  services, new  services, new  services222"
    },
    {
        "userId": 16,
        "fullName": "Emily white",
        "email": "roz",
        "phone": "123",
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "new  services222, new  services, new  services, new  services, Standard Room Booking"
    },
    {
        "userId": 8,
        "fullName": "fl",
        "email": "roz",
        "phone": "123",
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "new  services, new  services, new  services, new  services222"
    },
    {
        "userId": 38,
        "fullName": "Hoshir",
        "email": "roz",
        "phone": "123",
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "new  services222, new  services, new  services, new  services"
    },
    {
        "userId": 42,
        "fullName": "kevin",
        "email": "roz",
        "phone": "123",
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "new  services222, new  services, new  services, Deluxe Room Booking, new  services"
    },
    {
        "userId": 43,
        "fullName": "Lalo Salamanca",
        "email": "lalo@gmail.com",
        "phone": "07111111111",
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "new  services, Deluxe Room Booking, Standard Room Booking, new  services, new  services, new  services222"
    },
    {
        "userId": 48,
        "fullName": "Lalo Salamanca",
        "email": "lalo2@gmail.com",
        "phone": "07111111111",
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "new  services, new  services, new  services, new  services222"
    },
    {
        "userId": 53,
        "fullName": "Lalo Salamanca",
        "email": "lalo@gmail.com",
        "phone": "07111111111",
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "Spa Treatment"
    },
    {
        "userId": 26,
        "fullName": "Pedro2",
        "email": "roz",
        "phone": "123",
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "new  services, new  services, new  services, new  services222"
    },
    {
        "userId": 52,
        "fullName": "saul goodman",
        "email": "bettercaulsaul@gmail.com",
        "phone": null,
        "dateCreated": null,
        "address": null,
        "city": null,
        "postalCode": null,
        "avatarUrl": null,
        "notes": null,
        "staffServices": "Deluxe Room Booking"
    }
]
